django_test/locallibrary/locallibrary/catalog/urls.py
#our url file
#for this application - I'm not totally sure why we're crerating a special applicatoin here
# I really don't know. hopefully it will become obvious sooner or later

from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^books/$', views.BookListView.as_view(), name='books'),
	url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
]

django_test/locallibrary/locallibrary/locallibrary/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
	url(r'^catalog/', include('catalog.urls')),
]

urlpatterns += [
	url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Add django site authentication urls - for login, logout, password management)
urlpatterns += [
	url(r'^accounts/', include('django.contrib.auth.urls')),

]

# use static() to add url mapping to serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_test/locallibrary/locallibrary/catalog/models.py
from django.db import models
import uuid  # required for unique book instances

# Create your models here.

class Genre(models.Model):
	# model representing a bok genre

	name = models.CharField(max_length=200, help_text="Enter a book genre")

	def __str__(self):
		# string for representing the mode object
		return self.name

class Book(models.Model):

	#model representing a book (but not a specific copy of a book)

	title = models.CharField(max_length = 200)
	author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
	#foreign key is used becaues book can only have one author, but authors can have multiple books
	#author is a string rathr than object becaues it hasn't been delared yet
	summary = models.TextField(max_length = 1000, help_text = "Enter a brief descriptionof the book")
	isbn = models.CharField('ISBN', max_length=13, help_text='13 characters')
	genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
	#many to many field as each genre can contain many books. books can cover many genres
	#as genre class alreayd defined we can specify it as an object

	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse('book-detail', args[str(self.id)])

	#creates a string to define our genre - we use this for the display genre in admin
	def display_genre(self):
		return ', '.join([genre.name for genre in self.genre.all()[:3] ])
	display_genre.short_description= 'Genre'


class BookInstance(models.Model):
	# model representing a specific copy of a book - i.e. that can be borrowed from library
	id = models.UUIDField(primary_key= True, default=uuid.uuid4, help_text="Unique ID for this book")
	book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
	imprint = models.CharField(max_length = 200)
	due_back = models.DateField(null=True, blank=True)

	LOAN_STATUS = (
		('m', 'Maintenance'),
		('o', 'On Loan'),
		('a', 'Available'),
		('r', 'Reserved'),
		)

	status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

	class Meta:
		ordering = ["due_back"]
	

	def __str__(self):
		return '%s (%s)' %(self.id, self.book.title)
	


class Author(models.Model):
	# model representing an author
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length= 100)
	date_of_birth=models.DateField(null=True, blank=True)
	date_of_death= models.DateField('Died', null=True, blank=True)
	
	def get_absolute_url(self):
		return reverse('author-detail', args=[str(self.id)])

	
	def __str__(self):
		return '%s, %s' % (self.last_name, self.first_name)

django_test/locallibrary/locallibrary/catalog/views.py
from django.shortcuts import render
from .models import *
from django.views import generic

# Create your views here.

def index(request):
	#view function for homepage of site
	
	#we genereate counts of some of the main objects
	num_books = Book.objects.all().count()
	num_instances = BookInstance.objects.all().count()
	#available books
	num_instances_available = BookInstance.objects.filter(status='a').count()
	num_authors = Author.objects.count() # all is apparently implied by default?

	#get num visits by session
	num_visits = request.session.get('num_visits',0)
	request.session['num_visits'] = num_visits +1


	#we render the html template index with the data in the context variable
	return render(
		request, 'index.html',
 context={'num_books': num_books, 
'num_instances': num_instances, 'num_instances_available':num_instances_available,
'num_authors':num_authors, 'num_visits':num_visits}) # appeneded num visits





class BookListView(generic.ListView):
	model = Book
	#context_object_name = 'my_book_lis' # your own name for the list
	#queryset = Book.objects.filer(title_icontains='war')[:5] # customised query
	#template_name = 'books/my_arbitrary_template_name_list.html'# overwrite the default expected save location
	paginate_by = 15



#detail view class, to make this very easy also!
class BookDetailView(generic.DetailView):
	model = Book

django_test/locallibrary/locallibrary/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

{% block title %}<title> Local Library </title> {%endblock%}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href=""https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- add addition css in static file -->
{%load static %}
<link rel="stylesheet" href="{%static 'css/styles.css' %}">
</head>

<body>

<div class="container-fluid">
	<div class="row">
	{% block sidebar %}
	<ul class="sidebar-nav">
		<li><a href="{% url 'index' %}">Home</a></li>
		<li><a href="{% url 'books' %}">All books</a></li>
		<li><a href=""> All Authors</a></li>
	</ul>
	{% endblock %}
	</div>
	<div class="col-sm-10">
	{% block content %}{% endblock %}
	<!-- our pagination block here, which only occurs if trying to display paginated dat -->
	{% block pagination %}
	{% if is_paginated %}
		<div class="pagination">
			<span class="page-links">
				{% if page_obj.has_previous %}
					<a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
				{% endif %}
				<span class="page-current">
					Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
				</span>
				{% if page_obj.has_next %}
					<a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
				{% endif %}
				</span>
		</div>
	{% endif %}
	{% endblock %}
	</div>
</div>
</div>
</body>
</html>

django_test/locallibrary/locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>Title: {{book.title}}</h1>
	
	<p><strong>Author:</strong><a href="{% url author-detail' book.author.pk %}">{{book.author}}</a></p>
	<p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>  
    <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  
	
	<div style="margin-left:20px;margin-top:20px">
		<h4>Copies</h4>
		
		{% for copy in book.bookinstance_set.all %}
		<hr>
		<p class="{%if copy.status=='a' %}text-success{%elif copy.status=='d' %}text-danger{% else %}text-warning{% endif %}">{copy.get_status_display }}</p>
		{% if copy.status!='a' %}<p><strong>Due to be returned: </strong> {{copy.due_back}}</p>{% endif %}
		<p><strong>Imprint:</strong> {{copy.imprint}}</p>
		<p class="text-muted"><stong>ID:</strong> {{copy.id}}</p>
		{% endfor %}
	</div>
{% endblock %}

django_test/locallibrary/locallibrary/catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
	<h1>Book List</h1> 
	{% if book_list %}
	<ul>
		{% for book in book_list %}
		<li>
			<a href="{{book.get_absolute_url }}">{book.title}}</a> ({book.author}})
		</li>
		<% endfor %>
	</ul>
	{% else %}
	<p> There are no books in the library. </p>
	{% endif %}
{% endblock %}

django_test/locallibrary/locallibrary/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1> Local Library Home</h1>
	<p> The library has the following record counts:</p>
	<ul>
		<li><strong>Books:</strong>{{num_books}}</li>
		<li><strong>Copies:</strong>{{num_instances}}</li>
		<li><strong>Copies available:</strong>{{num_instances_available}}</li>
		<li><strong>Authors:</strong> {{num_authors}}</li>
	</ul>


<p> You have visited this page {{num_visits}}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}

django_test/locallibrary/locallibrary/templates/logged_out.html
{% extends "base_generic.html" %}

{% block content %}
<p>Logged out!</p>

<a href="{% url 'login'%}"> Click here to login again.</a>
{% endblock %}

django_test/locallibrary/locallibrary/templates/login.html
{% extends "base_generic.html" %}

{% block content %}

{% if form.errors %}
<p> You username and password didn't match. Please try again. </p>

{% endif %}


{% if next %}
	{% if user.is_authenticated %}
	<p>Your account doesn't have access to this page. To proceed,
		please login with an account tht has access.</p>
	{% else %}
	<p> Please login to see thsi page.</p>
	{% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}

<div>
	<td>{{ form.username.label_tag }}</td>
	<td>{{ form.username }}</td>
</div>
<div>
	<td>{{ form.password.label_tag }}</td>
	<td>{{ form.password }}</td>
</div>

<div>
	<input type="submit" value="login"/>
	<input type="hidden" name="next" value="{[ next }}" />	
</div>
</form>

{# assumes your setup password reset view in urlconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}